sudo: required
services:
    - docker

before_install:
    - docker build -t mikenol/docker-react -f Dockerfile.dev .

script:
    #- docker run -e CI=true mikenol/docker-react npm run test -- --coverage
    - docker run -e CI=true mikenol/docker-react npm run build

language: generic

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-002528515977"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
